
"use client";

import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Mail, Info, Sparkles, RefreshCw } from 'lucide-react';
import type { CreateEventFormData } from './CreateEventWizard';
import { generatePersonalizedInvitationText, type GenerateInvitationTextClientInput, type GenerateInvitationTextClientOutput } from '../actions';
import type { GuestInput, EventMood } from '@/types';

interface PreviewSendStepProps {
  eventData: Partial<CreateEventFormData>; 
  guestList: GuestInput[];
}

export function PreviewSendStep({ eventData, guestList }: PreviewSendStepProps) {
  const [sampleEmail, setSampleEmail] = useState<GenerateInvitationTextClientOutput | null>(null);
  const [isLoadingPreview, setIsLoadingPreview] = useState(false);
  const [previewError, setPreviewError] = useState<string | null>(null);

  const firstGuest = guestList?.[0];

  const fetchSampleEmail = async () => {
    if (!firstGuest || !eventData.name || !eventData.description || !eventData.mood) {
      setPreviewError("Not enough event or guest data to generate a preview.");
      setSampleEmail(null);
      return;
    }
    setIsLoadingPreview(true);
    setPreviewError(null);
    try {
      const inputForAI: GenerateInvitationTextClientInput = {
        eventName: eventData.name,
        eventDescription: eventData.description,
        eventMood: eventData.mood as EventMood, 
        guestName: firstGuest.name,
      };
      const result = await generatePersonalizedInvitationText(inputForAI);

      if (result.success) {
        setSampleEmail(result);
      } else {
        setPreviewError(result.message || "Failed to generate email preview.");
        setSampleEmail(null);
      }
    } catch (error) {
      console.error("Error generating email preview:", error);
      setPreviewError("An unexpected error occurred while generating the preview.");
      setSampleEmail(null);
    } finally {
      setIsLoadingPreview(false);
    }
  };

  useEffect(() => {
    fetchSampleEmail();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [eventData.name, eventData.description, eventData.mood, firstGuest?.name]); 

  const eventDate = eventData.date ? new Date(eventData.date).toLocaleDateString() : 'N/A';
  const eventTime = eventData.time || 'N/A';
  const eventLocation = eventData.location || 'N/A';

  return (
    <div className="space-y-6">
      <Alert>
        <Info className="h-4 w-4" />
        <AlertTitle>Review Invitation Details</AlertTitle>
        <AlertDescription>
          You're about to create the event and prepare invitations for <strong>{guestList.length}</strong> guest(s).
          Below is a sample of the invitation email content generated by AI for the first guest.
        </AlertDescription>
      </Alert>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center"><Mail className="mr-2 h-5 w-5 text-primary" />Sample Invitation Email</CardTitle>
          <CardDescription>
            For: {firstGuest?.name || 'Sample Guest'} ({firstGuest?.email || 'guest@example.com'})
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="p-4 border rounded-md bg-muted/30 min-h-[250px] whitespace-pre-wrap text-sm overflow-y-auto">
            {isLoadingPreview && <p className="text-muted-foreground">Generating preview...</p>}
            {previewError && <p className="text-destructive">{previewError}</p>}
            {sampleEmail?.success && sampleEmail.emailText && !isLoadingPreview && !previewError && (
              <>
                <p><strong>Subject:</strong> You're Invited to {eventData.name || 'Our Event'}!</p>
                <hr className="my-2"/>
                <p>{sampleEmail.greeting}</p>
                <br />
                <p>{sampleEmail.body}</p>
                <br />
                <p>{sampleEmail.closing}</p>
                <hr className="my-2 mt-4"/>
                <p className="font-semibold">Event Details (for context, actual details included in final email):</p>
                <p><strong>What:</strong> {eventData.name || 'Our Event'}</p>
                <p><strong>When:</strong> {eventDate} at {eventTime}</p>
                <p><strong>Where:</strong> {eventLocation}</p>
                <p className="mt-2 text-xs">To RSVP, guests will click their unique link: [Unique RSVP Link Will Be Here]</p>
                <p className="text-xs">We look forward to seeing you!</p>
              </>
            )}
             {!sampleEmail && !isLoadingPreview && !previewError && !firstGuest && (
                <p className="text-muted-foreground">Add guests in the previous step to see a preview.</p>
             )}
             {!sampleEmail?.success && !isLoadingPreview && !previewError && firstGuest && !sampleEmail?.message && (
                 <p className="text-muted-foreground">Could not generate preview. Ensure all event details are filled.</p>
             )}
          </div>
          <div className="flex gap-2">
            <Button type="button" variant="outline" onClick={fetchSampleEmail} disabled={isLoadingPreview || !firstGuest}>
              <RefreshCw className={`mr-2 h-4 w-4 ${isLoadingPreview ? 'animate-spin' : ''}`} />
              Regenerate Preview
            </Button>
            {/* Placeholder for more advanced AI adjustment */}
            <Button type="button" variant="outline" disabled>
              <Sparkles className="mr-2 h-4 w-4" /> Adjust with AI (Coming Soon)
            </Button>
          </div>
        </CardContent>
      </Card>
      <Alert variant="destructive">
        <Info className="h-4 w-4" />
        <AlertTitle>Important Note</AlertTitle>
        <AlertDescription>
          Clicking "Create Event & Prepare Invitations" will finalize the event details, create unique RSVP links for all guests, and add them to the database.
          The actual sending of emails will be handled by a separate process. Unique invitation links will be of the format: <code>https://your-app-domain/rsvp/unique-token</code>.
        </AlertDescription>
      </Alert>
    </div>
  );
}
